/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;


/**
 *
 * @author elalb
 */
public class JFrame_Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public JFrame_Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloL = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Contra = new javax.swing.JLabel();
        Camp_Correo = new javax.swing.JTextField();
        Camp_Contra = new javax.swing.JPasswordField();
        CrearC = new javax.swing.JLabel();
        Btnsalir = new javax.swing.JButton();
        Btnini = new javax.swing.JButton();
        Imglog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloL.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TituloL.setText("Login");

        Correo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Correo.setText("Correo electronico:");

        Contra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Contra.setText("Contraseña:");

        Camp_Correo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Camp_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_CorreoActionPerformed(evt);
            }
        });

        Camp_Contra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Camp_Contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_ContraActionPerformed(evt);
            }
        });

        CrearC.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        CrearC.setForeground(new java.awt.Color(0, 51, 255));
        CrearC.setText("Crear cuenta...");
        CrearC.setToolTipText("");
        CrearC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrearCMouseEntered(evt);
            }
        });

        Btnsalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btnsalir.setText("Salir");
        Btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsalirActionPerformed(evt);
            }
        });

        Btnini.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btnini.setText("Iniciar sesion");
        Btnini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtniniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(TituloL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Btnsalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Contra)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Camp_Correo)
                                    .addComponent(Correo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Camp_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CrearC))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Imglog)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Btnini))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(TituloL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Correo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Camp_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CrearC)
                        .addGap(18, 18, 18)
                        .addComponent(Contra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Camp_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addComponent(Imglog, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnsalir)
                    .addComponent(Btnini))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Camp_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camp_CorreoActionPerformed

    private void CrearCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCMouseClicked
JFrame_CrearCuenta CC = new JFrame_CrearCuenta();
CC.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_CrearCMouseClicked

    private void Camp_ContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_ContraActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_Camp_ContraActionPerformed

    private void CrearCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearCMouseEntered

    private void BtnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsalirActionPerformed
System.exit(0);
    }//GEN-LAST:event_BtnsalirActionPerformed

    private void BtniniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtniniActionPerformed
System.exit(0);
    }//GEN-LAST:event_BtniniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnini;
    private javax.swing.JButton Btnsalir;
    private javax.swing.JPasswordField Camp_Contra;
    private javax.swing.JTextField Camp_Correo;
    private javax.swing.JLabel Contra;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel CrearC;
    private javax.swing.JLabel Imglog;
    private javax.swing.JLabel TituloL;
    // End of variables declaration//GEN-END:variables
}
