/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;

import javax.swing.JOptionPane;

/**
 *
 * @author elalb
 */
public class JFrame_CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_CrearCuenta
     */
    public JFrame_CrearCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        BtnOcu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CorreoCC = new javax.swing.JLabel();
        ContraCC = new javax.swing.JLabel();
        Camp_CorreoCC = new javax.swing.JTextField();
        Camp_ContraCC = new javax.swing.JPasswordField();
        CContra = new javax.swing.JLabel();
        Camp_CContra = new javax.swing.JPasswordField();
        BtnOcu = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        Camp_Nombre = new javax.swing.JTextField();
        Nombre1 = new javax.swing.JLabel();
        Btnvolvercc = new javax.swing.JButton();
        Btnver = new javax.swing.JButton();
        Btnfinalizar = new javax.swing.JButton();
        ImgCC = new javax.swing.JLabel();
        GenContra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CorreoCC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CorreoCC.setText("Correo electronico:");

        ContraCC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ContraCC.setText("Contraseña:");

        Camp_CorreoCC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Camp_CorreoCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_CorreoCCActionPerformed(evt);
            }
        });

        Camp_ContraCC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Camp_ContraCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_ContraCCActionPerformed(evt);
            }
        });

        CContra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CContra.setText("Confirmar Contraseña:");

        Camp_CContra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Camp_CContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_CContraActionPerformed(evt);
            }
        });

        BtnOcu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnOcu.setText("Ocultar");
        BtnOcu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnOcu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnOcuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnOcuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnOcuMouseExited(evt);
            }
        });
        BtnOcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOcuActionPerformed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Nombre.setText("Crear cuenta");

        Camp_Nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Camp_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_NombreActionPerformed(evt);
            }
        });

        Nombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre1.setText("Nombre completo:");

        Btnvolvercc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btnvolvercc.setText("Volver");
        Btnvolvercc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btnvolvercc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnvolverccActionPerformed(evt);
            }
        });

        Btnver.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btnver.setText("Ver");
        Btnver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btnver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnverMouseExited(evt);
            }
        });
        Btnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnverActionPerformed(evt);
            }
        });

        Btnfinalizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Btnfinalizar.setText("Crear cuenta");
        Btnfinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btnfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnfinalizarActionPerformed(evt);
            }
        });

        GenContra.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        GenContra.setForeground(new java.awt.Color(0, 51, 255));
        GenContra.setText("Generar contraseña...");
        GenContra.setToolTipText("");
        GenContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GenContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenContraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GenContraMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(Nombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btnver)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btnvolvercc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btnfinalizar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ImgCC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GenContra))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ContraCC)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Camp_ContraCC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnOcu))
                            .addComponent(CContra)
                            .addComponent(Camp_CContra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Camp_CorreoCC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CorreoCC, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Camp_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Nombre)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(ImgCC)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Nombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Camp_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(CorreoCC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Camp_CorreoCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ContraCC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Camp_ContraCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btnver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnOcu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(GenContra)
                        .addGap(18, 18, 18)
                        .addComponent(CContra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Camp_CContra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btnfinalizar)
                            .addComponent(Btnvolvercc))
                        .addGap(33, 33, 33))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Camp_CorreoCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_CorreoCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camp_CorreoCCActionPerformed

    private void Camp_ContraCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_ContraCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camp_ContraCCActionPerformed

    private void Camp_CContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_CContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camp_CContraActionPerformed

    private void Camp_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camp_NombreActionPerformed

    private void BtnfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnfinalizarActionPerformed
JFrame_Login L = new JFrame_Login();
L.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_BtnfinalizarActionPerformed

    private void BtnvolverccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnvolverccActionPerformed
JFrame_Login L = new JFrame_Login();
L.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_BtnvolverccActionPerformed

    private void GenContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenContraMouseClicked
ClasePass cp = new ClasePass();
cp.getClass();
String contras;
        String ObtenerContra = cp.ObtenerContra();
        cp.ObtenerContra(cp.MINUSCULAS+cp.MAYUSCULAS+cp.ESPECIALES,10);
contras=ObtenerContra;
Camp_ContraCC.setText(contras);
    }//GEN-LAST:event_GenContraMouseClicked

    private void GenContraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenContraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_GenContraMouseEntered

    private void BtnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnverActionPerformed

    private void BtnverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnverMouseClicked
boolean a=true;
char i = 0;
        if(a){
            Camp_ContraCC.setEchoChar((char)0);
            a=false;
        }
            else{
                    Camp_ContraCC.setEchoChar(i);
                    a=true;
                    }
        Btnver.setVisible(false);
        BtnOcu.setVisible(true);
    }//GEN-LAST:event_BtnverMouseClicked

    private void BtnverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnverMouseEntered

    }//GEN-LAST:event_BtnverMouseEntered

    private void BtnverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnverMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnverMouseExited

    private void BtnOcuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOcuMouseClicked
boolean a=true;
char i = 0;
        if(a){
            Camp_ContraCC.setEchoChar('*');
            a=false;
        }
            else{
                    Camp_ContraCC.setEchoChar(i);
                    a=true;
                    }
        Btnver.setVisible(true);
        BtnOcu.setVisible(false);
    }//GEN-LAST:event_BtnOcuMouseClicked

    private void BtnOcuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOcuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOcuMouseEntered

    private void BtnOcuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOcuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOcuMouseExited

    private void BtnOcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOcuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOcuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOcu;
    private javax.swing.JButton Btnfinalizar;
    private javax.swing.JButton Btnver;
    private javax.swing.JButton Btnvolvercc;
    private javax.swing.JLabel CContra;
    private javax.swing.JPasswordField Camp_CContra;
    private javax.swing.JPasswordField Camp_ContraCC;
    private javax.swing.JTextField Camp_CorreoCC;
    private javax.swing.JTextField Camp_Nombre;
    private javax.swing.JLabel ContraCC;
    private javax.swing.JLabel CorreoCC;
    private javax.swing.JLabel GenContra;
    private javax.swing.JLabel ImgCC;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    // End of variables declaration//GEN-END:variables
}
